/*
 * SPDX-License-Identifier: GPL-3.0-only
 */

#include "common.h"
#include "audio_transport.h"
#include "audio_config.h"
#include "pkt.h"

#include "esp_lc3_enc.h"
#include "esp_lc3_dec.h"

#include "esp_task_wdt.h"
#include "esp_log.h"
#include "esp_check.h"
#include "esp_sleep.h"
#include "esp_timer.h"

#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "driver/rtc_io.h"

#include <stdlib.h>
#include <string.h>

static const char *TAG = "appI2S";

#define I2S_BCLK_PIN GPIO_NUM_1 // I2S bit clock io number
#define I2S_WS_PIN GPIO_NUM_2 // I2S word select io number
#define I2S_DOUT_PIN GPIO_NUM_10 // I2S data out io number
#define I2S_DIN_PIN GPIO_NUM_3 // I2S data in io number

static i2s_chan_handle_t s_i2s_tx;
static i2s_chan_handle_t s_i2s_rx;

#define AUDIO_NUM_CHAN 2

#define JITTER_CAPACITY 64 // slots
#define MIC_HISTORY_SIZE 32

#define LC3_FRAME_DMS (AUDIO_LC3_FRAME_US / 100)
#define MIC_BITS_PER_SAMPLE 16
#define SPK_FRAME_SAMPLES (AUDIO_SAMPLE_RATE / 1000 * AUDIO_LC3_FRAME_US / 1000)

static TaskHandle_t s_play_task = NULL;
static TaskHandle_t s_mic_task = NULL;
static bool s_open = false;

#if AUDIO_MIC_ENABLE && AUDIO_LC3_MIC_ENABLE
static void *s_enc;
static int s_enc_in_size; // PCM bytes consumed per encode
static int s_enc_out_size; // max encoded bytes produced per encode
static int16_t *s_mic_pcm; // 16-bit PCM
static uint8_t *s_mic_enc; // encoded LC3 frame
#endif

#if AUDIO_LC3_SPK_ENABLE
static void *s_dec;
static uint8_t *s_spk_pcm; // decoded PCM out
#endif

static void i2s_periph_disable_pins(void)
{
	gpio_num_t i2s_pins[] = { I2S_BCLK_PIN, I2S_WS_PIN };
	gpio_config_t io_conf = { .mode = GPIO_MODE_OUTPUT,
				  .pull_up_en = GPIO_PULLUP_DISABLE,
				  .pull_down_en = GPIO_PULLDOWN_ENABLE };

	for (int i = 0; i < 2; i++) {
		io_conf.pin_bit_mask = BIT64(i2s_pins[i]),
		gpio_config(&io_conf);

		gpio_set_level(i2s_pins[i], 0);
		gpio_hold_en(i2s_pins[i]);
	}

	gpio_deep_sleep_hold_en();
}

static void i2s_periph_init_std_duplex(void)
{
	if (s_i2s_rx != NULL || s_i2s_tx != NULL)
		return;

	gpio_hold_dis(I2S_BCLK_PIN);
	gpio_hold_dis(I2S_WS_PIN);

	/* Setp 1: Determine the I2S channel configuration and allocate both channels
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role */
	i2s_chan_config_t chan_cfg =
		I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);

	chan_cfg.auto_clear = true;

	ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, &s_i2s_tx, &s_i2s_rx));

	/* Step 2: Setting the configurations of standard mode, and initialize rx & tx channels
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */

	i2s_std_config_t std_cfg = {
        .clk_cfg  = I2S_STD_CLK_DEFAULT_CONFIG(48000),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,    // some codecs may require mclk signal, this example doesn't need it
            .bclk = I2S_BCLK_PIN,
            .ws   = I2S_WS_PIN,
            .dout = I2S_DOUT_PIN,
            .din  = I2S_DIN_PIN,        // In duplex mode, bind output and input to a same gpio can loopback internally
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv   = false,
            },
        },
    };

	// PCM5102A
	// FMT->LOW: Use I2S STD mode
	i2s_std_slot_config_t tx_slot = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(
		I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO);

	// INMP441 / ICS43434
	i2s_std_slot_config_t rx_slot = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(
		I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_MONO);
	// L/R(SEL)->LOW: Use left slot mask
	rx_slot.slot_mask = I2S_STD_SLOT_LEFT;

	/* Initialize the channels */
	std_cfg.slot_cfg = tx_slot;
	ESP_ERROR_CHECK(i2s_channel_init_std_mode(s_i2s_tx, &std_cfg));

	std_cfg.slot_cfg = rx_slot;
	ESP_ERROR_CHECK(i2s_channel_init_std_mode(s_i2s_rx, &std_cfg));
}

static void audio_play_task(void *param)
{
#if AUDIO_LC3_SPK_ENABLE
	uint8_t enc[2 * AUDIO_SPK_NBYTE];
#else
	uint8_t data[AUDIO_BUF_SIZE];
#endif
	int stat_total = 0, stat_conceal = 0;

	ESP_LOGI(TAG, "Playback starting");

	while (s_play_task) {
#if AUDIO_LC3_SPK_ENABLE
		jitter_frame_t kind = audio_transport_recv(enc);
		uint32_t bytes =
			SPK_FRAME_SAMPLES * AUDIO_NUM_CHAN * sizeof(int16_t);

		// No history yet: emit silence rather than buzzing PLC.
		if (kind == JITTER_FRAME_PREBUFFER) {
			memset(s_spk_pcm, 0, bytes);
		} else {
			esp_audio_dec_in_raw_t raw = {
				.buffer = enc,
				.len = sizeof(enc),
				.frame_recover =
					kind == JITTER_FRAME_OK ?
						ESP_AUDIO_DEC_RECOVERY_NONE :
						ESP_AUDIO_DEC_RECOVERY_PLC,
			};
			esp_audio_dec_out_frame_t out = {
				.buffer = s_spk_pcm,
				.len = bytes,
			};
			esp_audio_dec_info_t info;
			esp_lc3_dec_decode(s_dec, &raw, &out, &info);
			bytes = out.decoded_size;
		}
		i2s_channel_write(s_i2s_tx, s_spk_pcm, bytes, NULL,
				  portMAX_DELAY);
#else
		jitter_frame_t kind = audio_transport_recv(data);

		i2s_channel_write(s_i2s_tx, data, sizeof(data), NULL,
				  portMAX_DELAY);
#endif

		stat_total++;
		if (kind == JITTER_FRAME_CONCEAL)
			stat_conceal++;

		if (stat_total % 1000 == 0)
			ESP_LOGI(TAG, "Play stat total=%d concealed=%d",
				 stat_total, stat_conceal);
	}
	vTaskDelete(NULL);
}

#if AUDIO_MIC_ENABLE && AUDIO_LC3_MIC_ENABLE
static void mic_enc_close(void)
{
	if (s_enc != NULL) {
		esp_lc3_enc_close(s_enc);
		s_enc = NULL;
	}
	free(s_mic_pcm);
	free(s_mic_enc);
	s_mic_pcm = NULL;
	s_mic_enc = NULL;
}

static int mic_enc_open(void)
{
	esp_lc3_enc_config_t enc_cfg = {
		.sample_rate = AUDIO_SAMPLE_RATE,
		.bits_per_sample = MIC_BITS_PER_SAMPLE,
		.channel = 1,
		.frame_dms = LC3_FRAME_DMS,
		.nbyte = AUDIO_MIC_NBYTE,
		.len_prefixed = false,
	};

	if (esp_lc3_enc_open(&enc_cfg, sizeof(enc_cfg), &s_enc) !=
	    ESP_AUDIO_ERR_OK)
		return -1;
	if (esp_lc3_enc_get_frame_size(s_enc, &s_enc_in_size,
				       &s_enc_out_size) != ESP_AUDIO_ERR_OK)
		goto err;

	s_mic_pcm = malloc(s_enc_in_size);
	s_mic_enc = malloc(s_enc_out_size);
	if (s_mic_pcm == NULL || s_mic_enc == NULL)
		goto err;

	return 0;

err:
	mic_enc_close();
	return -1;
}
#endif

#if AUDIO_LC3_SPK_ENABLE
static void spk_dec_close(void)
{
	if (s_dec != NULL) {
		esp_lc3_dec_close(s_dec);
		s_dec = NULL;
	}
	free(s_spk_pcm);
	s_spk_pcm = NULL;
}

static int spk_dec_open(void)
{
	esp_lc3_dec_cfg_t dec_cfg = {
		.sample_rate = AUDIO_SAMPLE_RATE,
		.channel = AUDIO_NUM_CHAN,
		.bits_per_sample = MIC_BITS_PER_SAMPLE,
		.frame_dms = LC3_FRAME_DMS,
		.nbyte = AUDIO_SPK_NBYTE,
		.is_cbr = true,
		.len_prefixed = false,
		.enable_plc = true,
	};

	if (esp_lc3_dec_open(&dec_cfg, sizeof(dec_cfg), &s_dec) !=
	    ESP_AUDIO_ERR_OK)
		return -1;

	s_spk_pcm =
		malloc(SPK_FRAME_SAMPLES * AUDIO_NUM_CHAN * sizeof(int16_t));
	if (s_spk_pcm == NULL) {
		spk_dec_close();
		return -1;
	}

	return 0;
}
#endif

#if AUDIO_MIC_ENABLE
static void audio_mic_task(void *param)
{
	size_t nread;
#if AUDIO_LC3_MIC_ENABLE
	esp_audio_enc_in_frame_t in = { .buffer = (uint8_t *)s_mic_pcm };
	esp_audio_enc_out_frame_t out = { .buffer = s_mic_enc };

	// Instrumentation: confirm whether the encode keeps up with real time
	// (saturation) or the loop is spinning on read errors.
	int64_t enc_us = 0;
	int frames = 0, read_err = 0;
	int64_t window_start = esp_timer_get_time();
#else
	uint8_t data[AUDIO_BUF_SIZE];
#endif

	ESP_LOGI(TAG, "Mic capture starting");

	while (s_mic_task) {
#if AUDIO_LC3_MIC_ENABLE
		if (i2s_channel_read(s_i2s_rx, s_mic_pcm, s_enc_in_size, &nread,
				     portMAX_DELAY) != ESP_OK) {
			read_err++;
			vTaskDelay(1); // avoid a tight spin if reads error
			continue;
		}

		int64_t t0 = esp_timer_get_time();
		in.len = nread;
		out.len = s_enc_out_size;
		if (esp_lc3_enc_process(s_enc, &in, &out) == ESP_AUDIO_ERR_OK)
			audio_transport_send(s_mic_enc, out.encoded_bytes);
		enc_us += esp_timer_get_time() - t0;
		frames++;

		if (frames >= 500) {
			int64_t now = esp_timer_get_time();
			ESP_LOGI(
				TAG,
				"mic: enc avg=%lld us, %d frames in %lld ms, read_err=%d",
				enc_us / frames, frames,
				(now - window_start) / 1000, read_err);
			enc_us = 0;
			frames = 0;
			read_err = 0;
			window_start = now;
		}
#else
		if (i2s_channel_read(s_i2s_rx, data, sizeof(data), &nread,
				     portMAX_DELAY) != ESP_OK) {
			vTaskDelay(1);
			continue;
		}
		audio_transport_send(data, nread);
#endif
	}
	vTaskDelete(NULL);
}
#endif

void i2s_periph_start(void)
{
	if (!s_open || s_i2s_tx == NULL || s_play_task != NULL)
		return;

	i2s_channel_enable(s_i2s_rx);
	i2s_channel_enable(s_i2s_tx);

	xTaskCreate(audio_play_task, "audio_play", 4096, NULL, 3, &s_play_task);
#if AUDIO_MIC_ENABLE
	xTaskCreate(audio_mic_task, "audio_mic", 4096, NULL, 3, &s_mic_task);
#endif
}

void i2s_periph_stop(void)
{
	if (!s_open || s_i2s_tx == NULL || s_play_task == NULL)
		return;

	s_play_task = NULL;
	s_mic_task = NULL;
	// methods below act as cond waits for task finish
	i2s_channel_disable(s_i2s_rx);
	i2s_channel_disable(s_i2s_tx);
}

void i2s_periph_open(const host_conn_info_t *info)
{
	if (s_open)
		return;

	audio_transport_cfg_t cfg = {
		.local_port = info->udp_port,
		.remote_ip = info->ip,
		.remote_port = info->udp_port,
		.num_chan = AUDIO_NUM_CHAN,
		.jitter_enable = AUDIO_JITTER_ENABLE,
		.jitter_cap = JITTER_CAPACITY,
		.jitter_target = AUDIO_JITTER_DEPTH,
#if AUDIO_LC3_SPK_ENABLE
		.slot_size = 2 * AUDIO_SPK_NBYTE,
		.conceal = JITTER_CONCEAL_NONE,
#else
		.slot_size = AUDIO_BUF_SIZE,
		.conceal = JITTER_CONCEAL_PCM,
#endif
#if AUDIO_JITTER_ENABLE && AUDIO_MIC_ENABLE
		.history_size = MIC_HISTORY_SIZE, // retransmit mic on NACK
#else
		.history_size = 0,
#endif
	};

#if AUDIO_LC3_SPK_ENABLE
	if (spk_dec_open() != 0) {
		ESP_LOGE(TAG, "LC3 decoder open failed");
		return;
	}
#endif
#if AUDIO_MIC_ENABLE && AUDIO_LC3_MIC_ENABLE
	if (mic_enc_open() != 0) {
		ESP_LOGE(TAG, "LC3 encoder open failed");
#if AUDIO_LC3_SPK_ENABLE
		spk_dec_close();
#endif
		return;
	}
#endif

	if (audio_transport_open(&cfg, NULL) != 0) {
		ESP_LOGE(TAG, "Audio transport open failed");
#if AUDIO_MIC_ENABLE && AUDIO_LC3_MIC_ENABLE
		mic_enc_close();
#endif
#if AUDIO_LC3_SPK_ENABLE
		spk_dec_close();
#endif
		return;
	}
	s_open = true;
}

void i2s_periph_close(void)
{
	if (!s_open)
		return;

	i2s_periph_stop();

	audio_transport_close();
#if AUDIO_MIC_ENABLE && AUDIO_LC3_MIC_ENABLE
	mic_enc_close();
#endif
#if AUDIO_LC3_SPK_ENABLE
	spk_dec_close();
#endif
	s_open = false;
}

void i2s_periph_init(void)
{
	i2s_periph_init_std_duplex();
}

void i2s_periph_deinit(void)
{
	if (s_i2s_rx == NULL && s_i2s_tx == NULL)
		return;

	i2s_periph_close();

	i2s_del_channel(s_i2s_rx);
	i2s_del_channel(s_i2s_tx);
	s_i2s_rx = NULL;
	s_i2s_tx = NULL;

	i2s_periph_disable_pins();
}
