/*
 * SPDX-License-Identifier: GPL-3.0-only
 */

#include "common.h"

#include "esp_log.h"
#include "esp_check.h"

#include "driver/i2s_std.h"
#include "driver/gpio.h"

#define I2S_BCLK_PIN GPIO_NUM_1 // I2S bit clock io number
#define I2S_WS_PIN GPIO_NUM_2 // I2S word select io number
#define I2S_DOUT_PIN GPIO_NUM_10 // I2S data out io number
#define I2S_DIN_PIN GPIO_NUM_3 // I2S data in io number

i2s_chan_handle_t g_i2s_tx;
i2s_chan_handle_t g_i2s_rx;

static void i2s_periph_init_std_duplex(void)
{
	/* Setp 1: Determine the I2S channel configuration and allocate both channels
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role */
	i2s_chan_config_t chan_cfg =
		I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
	
	chan_cfg.auto_clear = true;

	ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, &g_i2s_tx, &g_i2s_rx));

	/* Step 2: Setting the configurations of standard mode, and initialize rx & tx channels
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */

	i2s_std_config_t std_cfg = {
        .clk_cfg  = I2S_STD_CLK_DEFAULT_CONFIG(44100),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,    // some codecs may require mclk signal, this example doesn't need it
            .bclk = I2S_BCLK_PIN,
            .ws   = I2S_WS_PIN,
            .dout = I2S_DOUT_PIN,
            .din  = I2S_DIN_PIN,        // In duplex mode, bind output and input to a same gpio can loopback internally
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv   = false,
            },
        },
    };

	// PCM5102A
	// FMT->LOW: Use I2S STD mode
	i2s_std_slot_config_t tx_slot = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(
		I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO);

	// INMP441 / ICS43434
	i2s_std_slot_config_t rx_slot = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(
		I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_MONO);
	// L/R(SEL)->LOW: Use left slot mask
	rx_slot.slot_mask = I2S_STD_SLOT_LEFT;

	/* Initialize the channels */
	std_cfg.slot_cfg = tx_slot;
	ESP_ERROR_CHECK(i2s_channel_init_std_mode(g_i2s_tx, &std_cfg));

	std_cfg.slot_cfg = rx_slot;
	ESP_ERROR_CHECK(i2s_channel_init_std_mode(g_i2s_rx, &std_cfg));
}

void i2s_periph_init(void)
{
	i2s_periph_init_std_duplex();

	i2s_channel_enable(g_i2s_rx);
	i2s_channel_enable(g_i2s_tx);
}

void i2s_periph_deinit(void)
{
	i2s_channel_disable(g_i2s_rx);
	i2s_channel_disable(g_i2s_tx);

	i2s_del_channel(g_i2s_rx);
	i2s_del_channel(g_i2s_tx);
}
