/*
 * SPDX-License-Identifier: GPL-3.0-only
 */

#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "freertos/portmacro.h"
#include "esp_check.h"
#include "sdkconfig.h"

#include <math.h>
#include <stdint.h>
#include <stdlib.h>


#define I2S_BCLK_PIN        GPIO_NUM_1      // I2S bit clock io number
#define I2S_WS_PIN          GPIO_NUM_2      // I2S word select io number
#define I2S_DOUT_PIN        GPIO_NUM_10     // I2S data out io number
#define I2S_DIN_PIN         GPIO_NUM_3      // I2S data in io number

static i2s_chan_handle_t                tx_chan;        // I2S tx channel handler
static i2s_chan_handle_t                rx_chan;        // I2S rx channel handler


static void i2s_example_init_std_duplex(void)
{
    /* Setp 1: Determine the I2S channel configuration and allocate both channels
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role */
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, &tx_chan, &rx_chan));

    /* Step 2: Setting the configurations of standard mode, and initialize rx & tx channels
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */

    i2s_std_config_t std_cfg = {
        .clk_cfg  = I2S_STD_CLK_DEFAULT_CONFIG(44100),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,    // some codecs may require mclk signal, this example doesn't need it
            .bclk = I2S_BCLK_PIN,
            .ws   = I2S_WS_PIN,
            .dout = I2S_DOUT_PIN,
            .din  = I2S_DIN_PIN,        // In duplex mode, bind output and input to a same gpio can loopback internally
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv   = false,
            },
        },
    };
    
    // PCM5102A 
    // FMT->LOW: Use I2S STD mode
    i2s_std_slot_config_t tx_slot = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_MONO);
    
    // INMP441 / ICS43434
    i2s_std_slot_config_t rx_slot = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_MONO);
    // L/R(SEL)->LOW: Use left slot mask
    rx_slot.slot_mask = I2S_STD_SLOT_LEFT;

    /* Initialize the channels */
    std_cfg.slot_cfg = tx_slot;
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &std_cfg));

    std_cfg.slot_cfg = rx_slot;
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(rx_chan, &std_cfg));
}

void app_main(void)
{
    i2s_example_init_std_duplex();

    size_t bytes_read;
    int32_t *buffer = malloc(1024); // Use 32-bit buffer to match slot config

    i2s_channel_enable(rx_chan);
    i2s_channel_enable(tx_chan);

    while (1) {
        // Read from ADC
        i2s_channel_read(rx_chan, buffer, 1024, &bytes_read, portMAX_DELAY);

        // Write to DAC
        i2s_channel_write(tx_chan, buffer, bytes_read, NULL, portMAX_DELAY);
    }
}